### ISSUE TITLE
country = pyc.get_shape("ITALY")

### ISSUE THREAD

**Issue by Prady96** [AleNegrini/PyCristoforo#31]
The error that I am receiving once after I run this line
 ```python
country = pyc.get_shape("ITALY")
```

Error Traceback
````python
Traceback (most recent call last):
  File "test_gen_points.py", line 3, in <module>
    country = pyc.get_shape("ITALY")
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pycristoforo/__init__.py", line 19, in get_shape
    return shape_py.setup_shape(key)
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pycristoforo/geo/shape.py", line 102, in setup_shape
    country_ids = eucountries_py.CountryList(constants_py.Constants.EU_PATH)
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pycristoforo/geo/countries.py", line 14, in __init__
    countries = utils_py.read_json(full_path)
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pycristoforo/utils/utils.py", line 12, in read_json
    data = json.load(f)
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/papli/.pyenv/versions/3.6.0/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8490275: ordinal not in range(128)
````

**Comment by AleNegrini** [comment]
Hello @Prady96,
I am not able to reproduce the error you reported. 

Here below the code I successfully run:
```
>>> import pycristoforo as pyc
>>> country = pyc.get_shape("ITALY")
>>> country
<shapely.geometry.multipolygon.MultiPolygon object at 0x10ecc56a0>
>>> points = pyc.geoloc_generation(country, 100, "Italy")
```
